---
codecov:
  branch: master

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
