enums = dict(
    age_ratings=dict(
        category={
            '1': 'ESRB',
            '2': 'PEGI',
            '3': 'CERO',
            '4': 'USK',
            '5': 'GRAC',
            '6': 'CLASS_IND',
            '7': 'ACB',
        },
        rating={
            '1': 'Three',
            '2': 'Seven',
            '3': 'Twelve',
            '4': 'Sixteen',
            '5': 'Eighteen',
            '6': 'RP',
            '7': 'EC',
            '8': 'E',
            '9': 'E10',
            '10': 'T',
            '11': 'M',
            '12': 'AO',
            '13': 'CERO_A',
            '14': 'CERO_B',
            '15': 'CERO_C',
            '16': 'CERO_D',
            '17': 'CERO_Z',
            '18': 'USK_0',
            '19': 'USK_6',
            '20': 'USK_12',
            '21': 'USK_18',
            '22': 'GRAC_ALL',
            '23': 'GRAC_Twelve',
            '24': 'GRAC_Fifteen',
            '25': 'GRAC_Eighteen',
            '26': 'GRAC_TESTING',
            '27': 'CLASS_IND_L',
            '28': 'CLASS_IND_Ten',
            '29': 'CLASS_IND_Twelve',
            '30': 'CLASS_IND_Fourteen',
            '31': 'CLASS_IND_Sixteen',
            '32': 'CLASS_IND_Eighteen',
            '33': 'ACB_G',
            '34': 'ACB_PG',
            '35': 'ACB_M',
            '36': 'ACB_MA15',
            '37': 'ACB_R18',
            '38': 'ACB_RC',
        },
        rating_age={
            '1': 3,
            '2': 7,
            '3': 12,
            '4': 16,
            '5': 18,
            '6': 17,
            '7': 3,
            '8': 1,
            '9': 10,
            '10': 13,
            '11': 17,
            '12': 18,
            '13': 1,
            '14': 12,
            '15': 15,
            '16': 17,
            '17': 18,
            '18': 1,
            '19': 6,
            '20': 12,
            '21': 18,
            '22': 1,
            '23': 12,
            '24': 15,
            '25': 18,
            '26': 18,
            '27': 1,
            '28': 10,
            '29': 12,
            '30': 14,
            '31': 16,
            '32': 18,
            '33': 1,
            '34': 13,
            '35': 15,
            '36': 15,
            '37': 18,
            '38': 18,
        },
    ),
    age_rating_contect_descriptions=dict(
        category={
            '1': 'PEGI',
            '2': 'ESRB',
        },
    ),
    characters=dict(
        gender={
            '0': 'Male',
            '1': 'Female',
            '2': 'Other',
        },
        species={
            '1': 'Human',
            '2': 'Alien',
            '3': 'Animal',
            '4': 'Android',
            '5': 'Unknown',
        },
    ),
    companies=dict(
        change_date_category={
            '0': 'YYYYMMMMDD',
            '1': 'YYYYMMMM',
            '2': 'YYYY',
            '3': 'YYYYQ1',
            '4': 'YYYYQ2',
            '5': 'YYYYQ3',
            '6': 'YYYYQ4',
            '7': 'TBD',
        },
        start_date_category={
            '0': 'YYYYMMMMDD',
            '1': 'YYYYMMMM',
            '2': 'YYYY',
            '3': 'YYYYQ1',
            '4': 'YYYYQ2',
            '5': 'YYYYQ3',
            '6': 'YYYYQ4',
            '7': 'TBD',
        },
    ),
    company_websites=dict(
        category={
            '1': 'official',
            '2': 'wikia',
            '3': 'wikipedia',
            '4': 'facebook',
            '5': 'twitter',
            '6': 'twitch',
            # '7': None,
            '8': 'instagram',
            '9': 'youtube',
            '10': 'iphone',
            '11': 'ipad',
            '12': 'android',
            '13': 'steam',
            '14': 'reddit',
            '15': 'itch',
            '16': 'epicgames',
            '17': 'gog',
            '18': 'discord',
        },
    ),
    games=dict(
        category={
            '0': 'main_game',
            '1': 'dlc_addon',
            '2': 'expansion',
            '3': 'bundle',
            '4': 'standalone_expansion',
            '5': 'mod',
            '6': 'episode',
            '7': 'season',
            '8': 'remake',
            '9': 'remaster',
            '10': 'expanded_game',
            '11': 'port',
            '12': 'fork',
        },
        status={
            '0': 'released',
            # '1': None,
            '2': 'alpha',
            '3': 'beta',
            '4': 'early_access',
            '5': 'offline',
            '6': 'cancelled',
            '7': 'rumored',
            '8': 'delisted',
        },
    ),
    game_version_features=dict(
        category={
            '0': 'boolean',
            '1': 'description',
        },
    ),
    game_version_feature_values=dict(
        included_feature={
            '0': 'NOT_INCLUDED',
            '1': 'INCLUDED',
            '2': 'PRE_ORDER_ONLY',
        },
    ),
    platforms=dict(
        category={
            '1': 'console',
            '2': 'arcade',
            '3': 'platform',
            '4': 'operating_system',
            '5': 'portable_console',
            '6': 'computer',
        },
    ),
    platform_version_release_dates=dict(
        category={
            '0': 'YYYYMMMMDD',
            '1': 'YYYYMMMM',
            '2': 'YYYY',
            '3': 'YYYYQ1',
            '4': 'YYYYQ2',
            '5': 'YYYYQ3',
            '6': 'YYYYQ4',
            '7': 'TBD',
        },
        region={
            '1': 'europe',
            '2': 'north_america',
            '3': 'australia',
            '4': 'new_zealand',
            '5': 'japan',
            '6': 'china',
            '7': 'asia',
            '8': 'worldwide',
            '9': 'korea',
            '10': 'brazil',
        },
    ),
    platform_websites=dict(
        category={
            '1': 'official',
            '2': 'wikia',
            '3': 'wikipedia',
            '4': 'facebook',
            '5': 'twitter',
            '6': 'twitch',
            # '7': None,
            '8': 'instagram',
            '9': 'youtube',
            '10': 'iphone',
            '11': 'ipad',
            '12': 'android',
            '13': 'steam',
            '14': 'reddit',
            '15': 'discord',
            '16': 'google_plus',
            '17': 'tumblr',
            '18': 'linkedin',
            '19': 'pinterest',
            '20': 'soundcloud',
        },
    ),
    release_dates=dict(
        category={
            '0': 'YYYYMMMMDD',
            '1': 'YYYYMMMM',
            '2': 'YYYY',
            '3': 'YYYYQ1',
            '4': 'YYYYQ2',
            '5': 'YYYYQ3',
            '6': 'YYYYQ4',
            '7': 'TBD',
        },
        region={
            '1': 'europe',
            '2': 'north_america',
            '3': 'australia',
            '4': 'new_zealand',
            '5': 'japan',
            '6': 'china',
            '7': 'asia',
            '8': 'worldwide',
            '9': 'korea',
            '10': 'brazil',
        },
    ),
    external_games=dict(
        category={
            '1': 'steam',
            '5': 'gog',
            '10': 'youtube',
            '11': 'microsoft',
            '13': 'apple',
            '14': 'twitch',
            '15': 'android',
            '20': 'amazon_asin',
            '22': 'amazon_luna',
            '23': 'amazon_adg',
            '26': 'epic_game_store',
            '28': 'oculus',
            '29': 'utomik',
            '30': 'itch_io',
            '31': 'xbox_marketplace',
            '32': 'kartridge',
            '36': 'playstation_store_us',
            '37': 'focus_entertainment',
        },
        media={
            '1': 'digital',
            '2': 'physical',
        },
    ),
    websites=dict(
        category={
            '1': 'official',
            '2': 'wikia',
            '3': 'wikipedia',
            '4': 'facebook',
            '5': 'twitter',
            '6': 'twitch',
            # '7': None,
            '8': 'instagram',
            '9': 'youtube',
            '10': 'iphone',
            '11': 'ipad',
            '12': 'android',
            '13': 'steam',
            '14': 'reddit',
            '15': 'itch',
            '16': 'epicgames',
            '17': 'gog',
            '18': 'discord',
        },
    ),
)
